
#CHANGE THESE BEFORE CREATING A WORLD!!!
#ANY CHANGES MADE WILL NOT AFFECT ALREADY GENERATED CHUNKS.
[General_Settings]
	#Setting this to false spawns only one time loot, setting this to true spawns loot generators.
	lootgenerators = false

[WorldGen_Base]
	#Average chunks between two bases.
	#Range: 10 ~ 50
	avg_dist = 25
	#Minimum chunks between two bases. MUST BE LESS THAN THE avg_dist SETTING.
	#Range: 3 ~ 30
	min_dist = 15

[WorldGen_Bunker]
	#Average chunks between two bases.
	#Range: 10 ~ 50
	avg_dist = 15
	#Minimum chunks between two bases. MUST BE LESS THAN THE avg_dist SETTING.
	#Range: 3 ~ 30
	min_dist = 5

[WorldGen_House]
	#Average chunks between two bases.
	#Range: 10 ~ 50
	avg_dist = 20
	#Minimum chunks between two bases. MUST BE LESS THAN THE avg_dist SETTING.
	#Range: 3 ~ 30
	min_dist = 10

[WorldGen_Tower]
	#Average chunks between two bases.
	#Range: 10 ~ 50
	avg_dist = 20
	#Minimum chunks between two bases. MUST BE LESS THAN THE avg_dist SETTING.
	#Range: 3 ~ 30
	min_dist = 10

