#Hex color code for the FPS counter
counterColor = "#FF0000"
#Position of the FPS counter on screen
#Allowed Values: TOP_LEFT, TOP_MIDDLE, TOP_RIGHT, CENTER_RIGHT, BOTTOM_RIGHT, BOTTOM_MIDDLE, BOTTOM_LEFT, CENTER_LEFT
counterPosition = "TOP_LEFT"

